/* AUTHENTICATION Reducer */
export const AUTHENTICATION_LOGIN = 'AUTHENTICATION_LOGIN';
export const AUTHENTICATION_LOGOUT = 'AUTHENTICATION_LOGOUT';

/* WEEK Reducer */
export const GET_CURRENT_WEEK_SUCCEED = 'GET_CURRENT_WEEK_SUCCEED';
export const INSTANCIATE_CURRENT_WEEK_SUCCEED = 'INSTANCIATE_CURRENT_WEEK_SUCCEED';

/* GAME Reducer */
export const GET_GAMES_SUCCEED = 'GET_GAMES_SUCCEED';