/* AUTHENTICATION Reducer */
export const AUTHENTICATION_LOGIN = 'AUTHENTICATION_LOGIN';
export const AUTHENTICATION_LOGOUT = 'AUTHENTICATION_LOGOUT';

/* WEEK Reducer */
export const WEEK_UPDATE = 'WEEK_UPDATE';
